//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labka3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_card
    {
        public int Id { get; set; }
        public string illHistory_ { get; set; }
        public Nullable<int> medId { get; set; }
    }
}
