//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labka3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities3 : DbContext
    {
        public Database1Entities3()
            : base("name=Database1Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<family_doctor> family_doctor { get; set; }
        public virtual DbSet<medical_card> medical_card { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Result_analyzes> Result_analyzes { get; set; }
        public virtual DbSet<special_doctor> special_doctor { get; set; }
    }
}
